# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.
# More information: https://docs.platform.sh/add-services.html
# Full list of available services: https://docs.platform.sh/add-services.html#available-services
{{- if .Services -}}
{{- range $value := .Services -}}
{{ $value.Name }}:
  type: {{ $value.Type }} # All available versions are: {{ $value.TypeVersions | join ", "}}
  {{- if $value.Disk }}
  disk: {{ $value.Disk }} # All available sizes are: {{ $value.DiskSizes | join ", "}}
  {{- end }}

{{ end -}}
{{ else }}
# relationships
# db:
#     type: postgresql:14
#     disk: 1024
{{ end -}}
